### PR TITLE
Add priority to DeclarativeContent

### PR DESCRIPTION
**Pull request by mdellweg**
This allows DeclarativeContent objects to bypass the batching process.

[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
This is the rightful heir of https://github.com/pulp/pulp/pull/3766.

**Comment by mdellweg** [comment]
After restructuring, i do not need that anymore for the pulp_deb plugin, still i think it might be useful for the problem @bmbouter described about the Maven Plugin.
Now setting a content unit to have priority does not stop batching immediately, but only prevents blocking while waiting on the in_q.
Ping @gmbnomis

**Comment by mdellweg** [comment]
@bmbouter As far as i am concerned, this is only "... could cause deadlock". The inefficiency should not be a big problem.

**Comment by bmbouter** [comment]
@mdellweg I filed the issue here:  https://pulp.plan.io/issues/4296

I want to close this PR for now so we can discuss it on that issue. Please reopen or let me know if you want to do this differently.

**Pull request closed without merging**
